title: "ChartMind"
description: "Research project description"
url: "https://tongli97.github.io"
baseurl: "/ChartMind"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Author
author:
  name: "Tong Li"
  email: "litong@zjut.edu.cn"
